### ISSUE TITLE
Paths are wrong on macOS

### ISSUE THREAD

**Issue by felixjchen** [Cyb3rN4u7/Python-Image-Converter#1]
![Screen Shot 2020-01-19 at 4 29 38 PM](https://user-images.githubusercontent.com/31393977/72688814-f8382f00-3ad8-11ea-8c98-33d9e4da333e.png)

Had to change ' \\\' to '/' to make this work on my macbook, can work around this with pathlib https://docs.python.org/3/library/pathlib.html

**Comment by rakovskij-stanislav** [comment]
Hello. There is patch for this thing: https://github.com/achimoraites/Python-Image-Converter/pull/2

**Comment by felixjchen** [comment]
looks good .

**Comment by achimoraites** [comment]
Thanks for your contributions @felixjchen and @rakovskij-stanislav 👏 !!!
