### ISSUE TITLE
Process gets killed

### ISSUE THREAD

**Issue by AgentSchmisch** [Cyb3rN4u7/Python-Image-Converter#12]
- i tried converting a folder that contains a larger amount of dng images
- the process is being killed by the OS if there are a large amount of images in the folder that is meant to be converted
- there are no images in the target folder after the cancellation

@achimoraites is there any chance that the files are kept in the ram and not directly written into the target after the conversion, it appears like it is that way

**Comment by achimoraites** [comment]
Can you please give me more details?
- What OS do you use?
- How many images have you tried to convert?
- Python version?
- Did you run the script locally or used the pip package?

**Comment by AgentSchmisch** [comment]
> Can you please give me more details?
> 
>     * What OS do you use?
>        Ubuntu 22.04
>     * How many images have you tried to convert?
>         around 90 dng's in a folder of 300 with cr3, jpg and dng
>     * Python version?
>       3.10
>     * Did you run the script locally or used the pip package?
>          pip in a virtual env

**Comment by achimoraites** [comment]
Good catch @AgentSchmisch 👏 !!!
Thanks for reporting it!
